# 05 - Data Search Example: Querying Fibers

## Going from an user defined position to the fiber spectra

To get all fibers within a defined aperture we must first find all shots that *may* contain fibers within that position. Because of the varying and non-contiguous footprint of VIRUS, the search for fibers is a two step process. In this notebook we will show we can go from in input location to all available fiber spectra.

In [13]:
%run ../survey.py
import numpy
import astropy.units as u
from astropy.coordinates import SkyCoord

Initiate the survey class:

In [14]:
S = Survey('hdr1')

Columns of the survey are now accessible as attributes to the Survey class

In [15]:
S.ra

array([149.88757 , 150.48582 , 149.77142 , ...,        nan,  30.001972,
        34.760807], dtype=float32)

In [16]:
S.shotid

array([20170103002, 20170103003, 20170105008, ..., 20181231012,
       20181231013, 20181231014])

The function get_shotlist() retrieves all shotids within a defined circular aperture or rectangular region. It operates on the Survey class and requires an astropy coords object as input. If a radius is given, then a circular region is assumed. It can either be an astropy quantity object or otherwise assumed to be in degrees. A rectangular region can be extracted if no radius is given. Both a width and height must be defined in degrees. For example, let's look around the region of our favourite object from a previous tutorial.

In [21]:
coords = SkyCoord(150.025513 * u.deg, 2.087767 * u.deg, frame='icrs')   

To find all shots located in a rectangle 0.5 degrees wide and 0.2 degrees high around the position:

In [39]:
shotlist = S.get_shotlist(coords, width=0.5, height=0.2)

or instead a circular aperture, note that both radius in degrees, arcmin, arcsec can work:

In [38]:
shotlist = S.get_shotlist(coords, radius=10*u.arcmin)
shotlist

array([20170105009, 20170106001, 20170106003, 20170107012, 20171119008,
       20171213017, 20171220015, 20171221016, 20171223010, 20171223014,
       20171225015, 20180110021, 20180113013, 20180114013, 20180120008,
       20180123009, 20180124010, 20180209009, 20180210006, 20180211014])

This ones lies within the cosmos repeat field, so we have lots of fibers.