# Accessing and Querying the Survey Class

The survey HDF5 file is a master look up table for each observation made by VIRUS for HETDEX. It can be accessed directly through the HDF5 survey file, or through the Survey class API. The Survey class includes information for each three dither set HETDEX observation in HDR1. It includes both science and calibration shots. Any quantity related to an individual dither is provided in an array of length three. Fundamental properties of a shot and quality assessment values for seeing (fwhm), astrometry, flux limits and transparency (response_4540) are tabulated to allow for querying of desired shots. 

We first introduce the basic API to query the Survey Class by sky coordinates to get a list of shots where fibers are located within that region. Later on in this notebook we show some basic querying of the Survey class and demonstrate a few examples.

## Initiate the Survey class

In [1]:
%matplotlib inline
import tables as tb
import numpy as np
import matplotlib.pyplot as plt

from astropy.table import Table
import astropy.units as u
from astropy.coordinates import SkyCoord

from hetdex_api.survey import Survey, FiberIndex

In [2]:
S = Survey('pdr1')

In [3]:
# convert to an astropy table format. Can remove any flagged shots if desired by setting return_good=True.
survey_table = S.return_astropy_table(return_good=False) 

In [4]:
survey_table

<Table length=3502>
   shotid     field         objid       ...  trajcpa   trajcra  shot_flag
   int64     bytes12       bytes18      ...  float32   float32     bool  
----------- ---------- ---------------- ... --------- --------- ---------
20170920008   dex-fall DEX00068_0_000_E ... 152.69672   24.5895      True
20170920009   dex-fall DEX00094_0_000_E ... 152.71495   31.6095      True
20170921018   dex-fall       DEX00001_0 ... 152.66785    6.4995      True
20170921020   dex-fall DEX00046_0_000_E ...  152.6847   18.6495      True
20170921021   dex-fall DEX00070_0_000_E ... 152.69867   25.1295      True
20170921022   dex-fall DEX00070_0_000_E ... 152.71495   31.3395      True
20170921025   dex-fall DEX00017_1_000_W ... 207.33266   10.8195      True
20170921026   dex-fall DEX00041_1_000_W ... 207.31718   17.2995      True
20170921029   dex-fall DEX00095_1_000_W ... 207.28346   31.8795      True
20170922021   dex-fall DEX00015_0_000_E ... 152.67038   10.2795      True
        ...        ...              ... ...       ...       ...       ...
20210810022   dex-fall        DEXfl1201 ... 148.92297  15.74763      True
20210810023   dex-fall        DEXfl0547 ... 148.92297  20.75196      True
20210810024   dex-fall        DEXfl1831 ... 148.92297 27.750586      True
20210818008   dex-fall        DEXfl0695 ... 146.37807  24.49788      True
20210818009   dex-fall        DEXfl1966 ... 146.37807 30.502125      True
20210818010   dex-fall        DEXfl1901 ... 146.37807 34.997623      True
20210818011   dex-fall        DEXfl0791 ... 201.13431   8.75208      True
20210826008 dex-spring        DEXsp6607 ...  293.8813 240.07066      True
20210828007 dex-spring        DEXsp6643 ... 294.31314 240.80075      True
20210830013 dex-spring        DEXsp6649 ... 291.92062 244.69333      True

It also converts RA and DEC into astropy coordinate objects.

In [5]:
S.coords

<SkyCoord (ICRS): (ra, dec) in deg
    [( 24.588702, 4.6900000e-04), ( 31.608569, 6.8900000e-04),
     (  6.498122, 5.2600000e-04), ..., (240.071344, 5.2579344e+01),
     (240.801501, 5.2778936e+01), (244.692454, 5.0994920e+01)]>

Shots are labeled based on their observation date and observation ID:

In [6]:
S.date

array([20170920, 20170920, 20170921, ..., 20210826, 20210828, 20210830],
      dtype=int32)

In [7]:
S.obsid

array([ 8,  9, 18, ...,  8,  7, 13], dtype=int32)

A specific shot can be linked either by an integer combination of these two values, called `shotid`, or the `DATEvOBS` form:

In [8]:
S.datevobs

array(['20170920v008', '20170920v009', '20170921v018', ...,
       '20210826v008', '20210828v007', '20210830v013'], dtype='<U12')

In [9]:
S.shotid

array([20170920008, 20170920009, 20170921018, ..., 20210826008,
       20210828007, 20210830013])

## Searching for shots near a sky coordinate wiht get_shotlist

Most users searching for observations will want to get a list of observations/shots at a specific sky position. Each shot has a single associated sky coordinate. We can retrieve a list of shots that may contain fibers in a specific region. However, because of the varying and non-contiguous footprint of VIRUS, this is not an immediate guarantee a region has been observed. You must further query fibers in each shot to determine this. See Notebook 02 to learn how to query with the Fibers Class API. 

This function which operates on the Survey class object. An astropy coordinates object is required as input.

In [10]:
coords = SkyCoord(11.628530 * u.deg, 0.081790 * u.deg, frame='icrs')

We can either search a rectangular region, width and height in degrees:

In [11]:
shotlist = S.get_shotlist(coords, width=0.5, height=0.2)

In [12]:
shotlist

array([20171119003, 20180106004, 20181003009, 20181005017, 20181107014,
       20191222012])

or we can search a circular aperture with a radius given in degress, or in an astropy quantity object:

In [13]:
shotlist = S.get_shotlist(coords, radius=10*u.arcmin)

In [14]:
shotlist

array([20171119003, 20180106004, 20181003009, 20181107014, 20191222012])

From here a user can take their shotlist and query the position on the Fibers class and see if their region of interest is observed in the survey.

## Basic querying for the Survey Class

The Survey HDF5 itself contains information about the quality of each observation. A user can query different parameters and plot up general shot quantities. For example, we can compare the distribution of throughput values (technically the response at 4540 AA) between the HETDEX spring and HETDEX fall fields:

### Example: Plotting up the canonical throughput value at 4540 AA

In [15]:
idx_spring = np.where( (S.field == 'dex-spring') * np.isfinite(S.response_4540) )

In [16]:
idx_fall = np.where( (S.field == 'dex-fall') * np.isfinite(S.response_4540))

In [17]:
plt.figure(figsize=(8,6))
plt.hist(S.response_4540[idx_spring], label = 'DEX-Spring', bins=20)
plt.hist(S.response_4540[idx_fall], label = 'DEX-Fall', bins=20)
plt.xlabel('Throughput at 4540 AA')
plt.ylabel('N OBS')
plt.legend()

## Access the survey H5 file

The hdfile attribute contains the link to the survey HDF5 file. Calling it will show you all the information in the HDF5 file. You may interact with this directly rather than using the Survey class initiation. 


In [18]:
S.hdfile

File(filename=/scratch/projects/hetdex/pdr1/survey/survey_pdr1.h5, title='PDR1 Survey File', mode='r', root_uep='/', filters=Filters(complevel=0, shuffle=False, bitshuffle=False, fletcher32=False, least_significant_digit=None))
/ (RootGroup) 'PDR1 Survey File'
/Survey (Table(3502,)) ''
  description := {
  "shotid": Int64Col(shape=(), dflt=0, pos=0),
  "field": StringCol(itemsize=12, shape=(), dflt=b'', pos=1),
  "objid": StringCol(itemsize=18, shape=(), dflt=b'', pos=2),
  "date": Int32Col(shape=(), dflt=0, pos=3),
  "obsid": Int32Col(shape=(), dflt=0, pos=4),
  "ra": Float64Col(shape=(), dflt=0.0, pos=5),
  "dec": Float64Col(shape=(), dflt=0.0, pos=6),
  "pa": Float64Col(shape=(), dflt=0.0, pos=7),
  "n_ifu": Int32Col(shape=(), dflt=0, pos=8),
  "fwhm_virus": Float32Col(shape=(), dflt=0.0, pos=9),
  "fwhm_virus_err": Float32Col(shape=(), dflt=0.0, pos=10),
  "response_4540": Float32Col(shape=(), dflt=0.0, pos=11),
  "ambtemp": Float32Col(shape=(), dflt=0.0, pos=12),
  "datevobs": Str

## Close the Survey H5 file after use

It is good practice to close any h5 files that are open when you no longer need to access new data from the h5 file

In [19]:
S.close()